name: your_project_name
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.8.0
  flutter_lints: ^5.0.0 
  flutter_bloc: ^8.0.0
  provider: ^6.0.0
  logger: 

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/img.jpg
    - assets/1.jpg
    - assets/2.jpg
    - assets/3.jpg
    - assets/4.jpg
    - assets/5.jpg
    - assets/6.jpg
    - assets/7.jpg
    - assets/8.jpg
  fonts:
    - family: BebasNeue
      fonts:
        - asset: fonts/BebasNeue-Regular.ttf